Favorites
WildCodeSchool/2022-03-JS-Toulouse-project-2-culture pull request #32
Opened 2022-05-03 13:35 UTC by msarava

save fav in local storage and sho in fav page

2022-05-03 18:34 UTC, pjamard approved these changes
ok

2022-05-03 18:34 UTC, pjamard approved these changes

2022-05-04 07:05 UTC, bastienwcs requested changes
C'est très bien, il y a juste un commentaire à supprimer et je valide tout ça :muscle:

2022-05-04 07:05 UTC, bastienwcs commented on frontend/src/components/CardTheme.jsx
> +  /**
il y a deux commentaires pour la même fonction : choisir celui que tu préfères

2022-05-04 07:41 UTC, msarava commented on frontend/src/components/CardTheme.jsx
> +  /**
c'est réglé

2022-05-04 07:41 UTC, bastienwcs approved these changes

2022-05-04 07:45 UTC, merged