Style
WildCodeSchool/2022-03-JS-Toulouse-project-2-culture pull request #52
Opened 2022-05-09 15:20 UTC by Xaboule

2022-05-09 15:32 UTC, bastienwcs requested changes

2022-05-09 15:32 UTC, bastienwcs commented on frontend/src/components/Map.css
> +  /* border: red solid 2px; */
:crying_cat_face:

2022-05-09 15:32 UTC, bastienwcs commented on frontend/src/components/carousel.css
> +  /* margin: 5rem 5rem; */
:crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face:

2022-05-09 15:32 UTC, bastienwcs commented on frontend/src/components/carousel.css
> +
supprimer les retours à la ligne

2022-05-09 15:32 UTC, bastienwcs commented on frontend/src/components/carousel.css
> +
suppriemr retour à la ligne

2022-05-09 15:32 UTC, bastienwcs commented on package.json
> +    "react-tsparticles": "^2.0.6"
ne pas modifier le package.json de la racine. 
SUpprimer la dépendance, l'installer dans frontend et refaire un npm run setup

2022-05-09 16:16 UTC, Xaboule commented on package.json
> +    "react-tsparticles": "^2.0.6"
J'ai pourtant tout réinstallé avec toi :'(

2022-05-10 06:55 UTC, bastienwcs commented
Reste le package.json à remettre e nordre, vient me voir pour qu'on fasse ça

2022-05-10 09:00 UTC, bastienwcs approved these changes

2022-05-10 09:00 UTC, merged